!/bin/sh

set -e

export OPENWRT_TARGET="$1"

export OPENWRT_PRITARGET=$(echo "${OPENWRT_TARGET}" | cut -d- -f1)
export OPENWRT_SUBTARGET=$(echo "${OPENWRT_TARGET}" | cut -d- -f2)

export OPENWRT_TARGET_="${PRITARGET}_${SUBTARGET}"

echo "OPENWRT_TARGET=${OPENWRT_TARGET}" >> "$GITHUB_ENV"
echo "OPENWRT_PRITARGET=${OPENWRT_PRITARGET}" >> "$GITHUB_ENV"
echo "OPENWRT_SUBTARGET=${OPENWRT_SUBTARGET}" >> "$GITHUB_ENV"
echo "OPENWRT_TARGET_=${OPENWRT_TARGET_}" >> "$GITHUB_ENV"
