name: Build OpenWrt Imagebuilder

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
jobs:
  build_firmware:
    strategy:
      fail-fast: false
      matrix:
        target:
          - ath79-nand
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo contrib/actions/install-dependencies.sh

      - name: Checkout OpenWrt
        run: contrib/actions/prepare-openwrt.sh

      - name: generate config
        run: contrib/actions/generate-config.sh ${{ matrix.target }}

      - name: Build
        run: contrib/actions/run-build.sh

      - name: tree openwrt
        run: tree openwrt

      - name: tree output
        run: tree output

      - name: Archive build logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}_logs
          path: openwrt/logs

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}_output
          path: output
